# Configuration file for air
root = "./src"
tmp_dir = "tmp"

[build]
cmd = "go build -o tmp/main ./src"
bin = "tmp/main"
include_ext = ["go"]
exclude_dir = ["vendor", "tmp", "node_modules"]
exclude_file = ["README.md"]
delay = 100
